//created on: 2014.12.08.
package rules

//list any import classes here.



//declare any global variables here



rule "1 week 1 kilo weight loss"
    when
        $p : Person()
        $m1 : WeightMeasureEvent( $v1 : value, person.ssn == $p.ssn )
	   from entry-point "Weight-EP"
        $m2 : WeightMeasureEvent( $v2: value, $v1-$v2 > 1000 ,
 	   person.ssn == $p.ssn, this != $m1 ,
	   this after [0, 7d] $m1 )  from entry-point "Weight-EP"
    then
System.out.println("Extreme weight loss: "+$v1/1000+"kg -> "+$v2/1000+"kg"); 
end
