//created on: 2014.12.08.
package rules.cep

//list any import classes here.
import hu.bme.diploma.a7e7yk.datamodel.health.vitalsigns.BloodPressureVitalSign;


//declare any global variables here


rule "HighBloodPressure warning"
    when
       $b : BloodPressureVitalSign( systolic.value > 140) from entry-point "bp-ep" 
    then
	System.out.println("Something is in the air");
	 System.out.println($b);
end
