//created on: 2014.12.02.
package rules

//list any import classes here.
import hu.bme.aut.diploma.model.Person
import hu.bme.aut.diploma.model.Diagnosis
import hu.bme.aut.diploma.model.Measurement


//declare any global variables here


rule "High blood pressure"
	ruleflow-group "HearthFailureGroup"
    when
     	$p : Person(  )
     	// not Diagnosis( snomedcode == "38341003" ) from $p.getDiagnosis() // high bloodpressure not in
     	Diagnosis( snomedcode == "161941007") from $p.getDiagnosis() //Dyspnea at resting
     	Measurement( type == "111973004", value > 150.0 ) from $p.getMeasurements()  //systolis
		Measurement( type == "90892000", value > 110 ) from $p.getMeasurements()//diastolic
    then
   		System.out.println("This is from the inside rule");
   		Diagnosis d = new Diagnosis();
   		d.setSnomedcode("38341003");
   		d.setHumanname("Hypertensive disorder, systemic arterial");
   		$p.getDiagnosis().add(d);

end
